# Beta Release starting very zero
version: '1.2.{build}'

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

branches:
  only:
  - master

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  - dotnet restore

build_script:
  - dotnet build .\CommandPrompt.sln

test_script:
  - dotnet test .\src\CommandPrompt.Tests\CommandPrompt.Tests.csproj

after_test:
  - echo  APPVEYOR_BUILD_VERSION = %APPVEYOR_BUILD_VERSION%
  - dotnet pack src/CommandPrompt/ -c Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

artifacts:
- path: 'src/CommandPrompt/bin/Release/*.nupkg'
  name: NuGetPackages

deploy:
- provider: NuGet
  api_key:
    secure: J9T92Vjh7Myn+NBHKDxje54wIc9/pDVUQqFs++LDvVCAihRzg7Ll3U9KEqZknP3K
  artifact: 'NuGetPackages'
